import NavBar from './components/NavBar/NavBar';
import './globals.css';
import './classes.css';

export const metadata = {
  title: 'Paintscape',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='text-white dark:secondaryBg'>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
